/**
 * Module resolution hooks — see alias-loader.mjs for why these exist.
 *
 * This lives in its own file rather than an inline `data:` URL because a data URL is terminated by
 * raw newlines, so a multi-line hook silently truncates and Node reports "Unexpected end of input"
 * from a location that does not appear in any source file.
 */

import { pathToFileURL } from 'node:url';

const root = pathToFileURL(process.cwd()).href;

/**
 * `$env/static/private` is generated by SvelteKit at build time and does not exist on disk, so any
 * script importing a module that reads it fails to resolve. Served here from `process.env` instead,
 * which is the same source SvelteKit itself reads (via dotenv) — so a script gets the real values
 * rather than a fixture, and a module that opens a database connection at load actually can.
 *
 * Deliberately a live proxy over `process.env` rather than a snapshot: the caller may well call
 * `dotenv.config()` after these hooks are registered but before the first import resolves.
 */
const ENV_SHIM = 'expositor:env-static-private';

export async function resolve(specifier, context, nextResolve) {
	if (specifier === '$env/static/private' || specifier === '$env/dynamic/private') {
		return { url: ENV_SHIM, format: 'module', shortCircuit: true };
	}

	const target = specifier.startsWith('$lib/')
		? `${root}/src/lib/${specifier.slice('$lib/'.length)}`
		: specifier;

	// `schema.js` does not exist on disk — the file is `schema.ts`. Vite rewrites the extension; bare
	// Node throws ERR_MODULE_NOT_FOUND. Retrying as `.ts` lets a script import the REAL server modules
	// (which all import `./schema.js`) instead of a hand-copied stand-in that could drift from the
	// schema it is meant to represent. Requires a TypeScript-capable loader such as tsx to be
	// registered alongside these hooks; without one the .ts resolve succeeds and the LOAD then fails,
	// which is a clear error rather than a silent wrong answer.
	try {
		const resolved = await nextResolve(target, context);
		return annotateJson(resolved);
	} catch (error) {
		if (error?.code === 'ERR_MODULE_NOT_FOUND' && target.endsWith('.js')) {
			return annotateJson(await nextResolve(`${target.slice(0, -3)}.ts`, context));
		}
		throw error;
	}
}

/**
 * Vite treats a .json import as JSON implicitly; Node requires an explicit `with { type: 'json' }`
 * attribute and throws ERR_IMPORT_ATTRIBUTE_MISSING without it. Supplying it here lets the source
 * files stay written for Vite, which is what actually ships.
 *
 * It must go on the *result*, not on the context passed downward: Node validates attributes at load
 * time against what the resolve hook returned, so a context-only version still throws.
 */
function annotateJson(resolved) {
	if (resolved.url.endsWith('.json')) {
		return { ...resolved, format: 'json', importAttributes: { type: 'json' } };
	}
	return resolved;
}

/**
 * Source for the `$env` shim resolved above.
 *
 * Emits a module that re-exports `process.env` both as named bindings and as `env`, covering the two
 * shapes SvelteKit offers (`static/private` destructures named constants; `dynamic/private` exports an
 * `env` object). Only keys present at load time can be named exports, which is why `dotenv.config()`
 * must run before the first import that needs one — the probe does exactly that.
 */
export async function load(url, context, nextLoad) {
	if (url !== ENV_SHIM) return nextLoad(url, context);

	// ⚠️ `.env` is read HERE, not left to the calling script.
	//
	// Module resolution runs before any of the importing script's own statements, so a script that calls
	// `dotenv.config()` at its top has still not done so by the time this shim loads — the named exports
	// would be generated from an empty `process.env` and the import would fail with "does not provide an
	// export named DATABASE_URL". That is exactly what happened on the first attempt. Reading the file
	// here makes the shim independent of the caller's ordering.
	await loadDotEnv();

	const names = Object.keys(process.env).filter((k) => /^[A-Za-z_][A-Za-z0-9_]*$/.test(k));
	const source = [
		'const env = process.env;',
		'export { env };',
		...names.map((k) => `export const ${k} = process.env[${JSON.stringify(k)}];`)
	].join('\n');

	return { format: 'module', shortCircuit: true, source };
}

/**
 * Populate `process.env` from `.env`, without overwriting anything already set.
 *
 * Uses dotenv when it resolves, and falls back to a minimal parser so the hook does not hard-depend on
 * it. Existing values win, matching dotenv's own default: a variable exported in the shell must beat
 * the file, or a script cannot be pointed at a different database for one run.
 */
async function loadDotEnv() {
	try {
		const dotenv = await import('dotenv');
		dotenv.config({ quiet: true });
		return;
	} catch {
		// Fall through to the minimal parser.
	}

	try {
		const { readFileSync } = await import('node:fs');
		const text = readFileSync(new URL('../.env', import.meta.url), 'utf8');
		for (const line of text.split('\n')) {
			const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
			if (!match) continue;
			const value = match[2].trim().replace(/^["']|["']$/g, '');
			if (process.env[match[1]] === undefined) process.env[match[1]] = value;
		}
	} catch {
		// No .env at all: leave process.env as-is. The consuming module will report the missing variable
		// itself, which is a clearer error than anything invented here.
	}
}
